# Generated by Django 4.2.11 on 2024-05-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'ordering': ['id'], 'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['rut'], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
